#!/bin/bash

# /etc/network/if-post-down.d/dhcpcd-sync
#
# Hook script provided by the 'tkl-dhcpcd-ifupdown-glue' package and part of
# TurnKey GNU/Linux network configuration.
#
# Removes denyinterfaces entry when interface is deconfigured.
# This ensures dhcp works again if the interface is later reconfigured to dhcp
# without an ifup cycle (e.g. manual dhcpcd invocation).

# shellcheck source=share/helper
source /usr/share/tkl-dhcpcd-ifupdown-glue/helper

_log_info "if-post-down hook running for $IFACE"

_init "$IFACE"

for _ipv in ip4 ip6; do
    _log_info "clearing $IFACE $_ipv related config from $DHCPCD_CONF (if found)"
    remove_deny_entry "$IFACE" $_ipv
done

_log_info "if-post-down hook finished for $IFACE"

exit 0
