#!/bin/bash

# /etc/network/if-pre-up.d/dhcpcd-sync
#
# Hook script provided by the 'tkl-dhcpcd-ifupdown-glue' package and part of
# TurnKey GNU/Linux network configuration.
#
# Keeps dhcpcd.conf in sync with /etc/network/interfaces so that
# interfaces configured as static are not also managed by dhcpcd.

# shellcheck source=share/helper
source /usr/share/tkl-dhcpcd-ifupdown-glue/helper

_log_info "if-pre-up hook running for $IFACE"

_init "$IFACE"

for info in _iface4_method _iface6_method; do
    read -r ipv method <<<"$info"
    # remove the entry if it exists regardless
    remove_deny_entry "$IFACE" "$ipv"
    if [[ "$method" == "dhcp" ]]; then
        _log_info "$IFACE $ipv is dhcp - nothing to do"
        continue
    else
        _log_info "$IFACE $ipv is ${method} - disabling dhcp"
        add_deny_entry "$IFACE" "$ipv"
    fi
done

_log_info "if-pre-up hook finished for $IFACE"

exit 0
